"""initial schema

Revision ID: 0b1699f23be3
Revises: 
Create Date: 2026-06-08 22:43:17.498699

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '0b1699f23be3'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('users',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('openid', sa.String(), nullable=False),
    sa.Column('nickname', sa.String(), nullable=True),
    sa.Column('role', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_users_openid'), ['openid'], unique=True)

    op.create_table('medical_reports',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('uploader_id', sa.Integer(), nullable=False),
    sa.Column('subject_id', sa.Integer(), nullable=True),
    sa.Column('report_type', sa.String(), nullable=False),
    sa.Column('report_type_label', sa.String(), nullable=True),
    sa.Column('report_date', sa.Date(), nullable=True),
    sa.Column('hospital', sa.String(), nullable=True),
    sa.Column('image_path', sa.String(), nullable=False),
    sa.Column('image_paths', sa.JSON(), nullable=True),
    sa.Column('status', sa.String(), nullable=False),
    sa.Column('raw_json', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['subject_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['uploader_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('medical_reports', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_medical_reports_hospital'), ['hospital'], unique=False)
        batch_op.create_index(batch_op.f('ix_medical_reports_report_date'), ['report_date'], unique=False)
        batch_op.create_index(batch_op.f('ix_medical_reports_report_type'), ['report_type'], unique=False)
        batch_op.create_index(batch_op.f('ix_medical_reports_subject_id'), ['subject_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_medical_reports_uploader_id'), ['uploader_id'], unique=False)

    op.create_table('medical_report_metrics',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('report_id', sa.Integer(), nullable=False),
    sa.Column('item_name', sa.String(), nullable=False),
    sa.Column('item_code', sa.String(), nullable=True),
    sa.Column('value_text', sa.String(), nullable=True),
    sa.Column('value_num', sa.Float(), nullable=True),
    sa.Column('unit', sa.String(), nullable=True),
    sa.Column('ref_range', sa.String(), nullable=True),
    sa.Column('ref_low', sa.Float(), nullable=True),
    sa.Column('ref_high', sa.Float(), nullable=True),
    sa.Column('abnormal_flag', sa.String(), nullable=True),
    sa.Column('seq', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['report_id'], ['medical_reports.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('medical_report_metrics', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_medical_report_metrics_item_code'), ['item_code'], unique=False)
        batch_op.create_index(batch_op.f('ix_medical_report_metrics_report_id'), ['report_id'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('medical_report_metrics', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_medical_report_metrics_report_id'))
        batch_op.drop_index(batch_op.f('ix_medical_report_metrics_item_code'))

    op.drop_table('medical_report_metrics')
    with op.batch_alter_table('medical_reports', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_medical_reports_uploader_id'))
        batch_op.drop_index(batch_op.f('ix_medical_reports_subject_id'))
        batch_op.drop_index(batch_op.f('ix_medical_reports_report_type'))
        batch_op.drop_index(batch_op.f('ix_medical_reports_report_date'))
        batch_op.drop_index(batch_op.f('ix_medical_reports_hospital'))

    op.drop_table('medical_reports')
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_users_openid'))

    op.drop_table('users')
    # ### end Alembic commands ###
