"""add content_hash to medical_reports

Revision ID: 8196b38fb683
Revises: 0b1699f23be3
Create Date: 2026-06-08 23:11:55.724911

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '8196b38fb683'
down_revision: Union[str, None] = '0b1699f23be3'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('medical_reports', schema=None) as batch_op:
        batch_op.add_column(sa.Column('content_hash', sa.String(), nullable=True))
        batch_op.create_index(batch_op.f('ix_medical_reports_content_hash'), ['content_hash'], unique=True)

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('medical_reports', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_medical_reports_content_hash'))
        batch_op.drop_column('content_hash')

    # ### end Alembic commands ###
