"""user avatar and favorite table rename

Revision ID: af6a6363811c
Revises: 6968f0bf48f6
Create Date: 2026-06-09 18:55:58.782909

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'af6a6363811c'
down_revision: Union[str, None] = '6968f0bf48f6'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('user_favorite',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('service_key', sa.String(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id', 'service_key', name='uq_user_service')
    )
    with op.batch_alter_table('user_favorite', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_user_favorite_user_id'), ['user_id'], unique=False)

    with op.batch_alter_table('medical_user_favorite', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_medical_user_favorite_user_id'))

    op.drop_table('medical_user_favorite')
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('avatar_path', sa.String(), nullable=True))

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_column('avatar_path')

    op.create_table('medical_user_favorite',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('user_id', sa.INTEGER(), nullable=False),
    sa.Column('service_key', sa.VARCHAR(), nullable=False),
    sa.Column('created_at', sa.DATETIME(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id', 'service_key', name=op.f('uq_user_service'))
    )
    with op.batch_alter_table('medical_user_favorite', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_medical_user_favorite_user_id'), ['user_id'], unique=False)

    with op.batch_alter_table('user_favorite', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_user_favorite_user_id'))

    op.drop_table('user_favorite')
    # ### end Alembic commands ###
